### PR TITLE
better user management

### PR DESCRIPTION
**Pull request by blamoo**

### CODE REVIEW

**Comment by sugoi-reader** [comment]
Wasn't expecting a PR haha

What's the deal?

**Comment by sugoi-reader** [comment]
The whole warning thing is kinda weird. Just output the new json file instead of overwriting stuff. User will do whatever he wants with the output.

**Comment by blamoo** [comment]
you cant pipe the output to sugoi.json because of the "Username: Password:" will be sent together
added a prompt after it and removed the duplicate function (fk vs code)

**Comment by blamoo** [comment]
You can't pipe the output to sugoi.json because of the "Username: Password:" will be sent together.
Added a prompt after it and removed the duplicate function.

**Comment by sugoi-reader** [comment]
Fine, whatever. ty for removing the upload thing btw

**Pull request merged**
